execute pathogen#infect()
set shell=/bin/bash
set number
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
syntax enable
set background=dark
colorscheme solarized
set title
set titlestring="modeline vim: %F"
let g:tex_flavor='latex'

noremap <F3>g :YcmCompleter GoTo<cr>
noremap <F3>r :YcmCompleter GoToReferences<cr>

filetype plugin indent on    " required
