#!/usr/bin/python
import configparser
import requests
import os
import webbrowser

config = configparser.ConfigParser()
config.read('/home/nick/.config/environment.conf')
zipCode = config['location']['zipcode']
state = config['location']['state']
city = config['location']['city']
apiKey = config['api']['openweathermap']

if(os.environ.get('BLOCK_BUTTON', 0) == '1'):
    webbrowser.open('https://www.wunderground.com/weather/us/{}/{}'.format(state, city))
#imperial, metric, or kelvin
units = 'imperial'
r = requests.get('http://api.openweathermap.org/data/2.5/weather?zip={}&units={}&APPID={}'.format(zipCode, units, apiKey))
result = r.json()
weather = result['weather'][0]['main']
temp = result['main']['temp']
print("{} {:.0f}°F".format(weather, temp))
print("{} {:.0f}°F".format(weather, temp))
print()


